src/uSeoToolkit.Umbraco.MetaFields/App_Plugins/uSeoToolkit/MetaFields/Interface/ContentApps/SeoSettings/seoSettings.html
=> Opens meta field links in separate tab

src/uSeoToolkit.Umbraco.MetaFields/App_Plugins/uSeoToolkit/MetaFields/Interface/ContentApps/SeoSettings/seoSettings.html, src/uSeoToolkit.Umbraco.MetaFields/App_Plugins/uSeoToolkit/MetaFields/css/main.css
=> Changed alert-box to use Umbraco styling

src/SeoToolkit.Umbraco.Sitemap.Core/Migrations/SitemapChangeFrequencyOptionalMigration.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Migrations/SitemapMigrationPlan.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Models/Database/SitemapPageTypeEntity.cs
Fixes issue #42, made nullable because there already is a null-check in the SitemapGenerator when using this field ;)
=> #42 - Made ChangeFrequency nullable for SitemapPageTypeEntity

src/SeoToolkit.Umbraco.Common.Core/Collections/ModuleCollection.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/41
=> Fix for the documentation links

src/SeoToolkit.Umbraco.MetaFields.Core/Common/Converters/SeoValueConverters/FieldSeoValueConverter.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Common/Converters/SeoValueConverters/MultiplePublishedContentSeoValueConverter.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Composers/MetaFieldsComposer.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/51
=> Support for multiple media picker

src/SeoToolkit.Umbraco.Redirects/App_Plugins/SeoToolkit/backoffice/Redirects/list.controller.js
Added the status code label to the overview, to align it with the create/edit overlay:
=> Added the status code as text to the redirects overview (#45)

src/SeoToolkit.Umbraco.Redirects.Core/Controllers/RedirectsController.cs, src/SeoToolkit.Umbraco.Redirects.Core/Interfaces/IRedirectsRepository.cs, src/SeoToolkit.Umbraco.Redirects.Core/Interfaces/IRedirectsService.cs, src/SeoToolkit.Umbraco.Redirects.Core/Repositories/RedirectsRepository.cs, src/SeoToolkit.Umbraco.Redirects.Core/Services/RedirectsService.cs, src/SeoToolkit.Umbraco.Redirects/App_Plugins/SeoToolkit/backoffice/Redirects/list.controller.js, src/SeoToolkit.Umbraco.Redirects/App_Plugins/SeoToolkit/backoffice/Redirects/list.html
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/67
=> Created some simple logic for searching within redirects

src/SeoToolkit.Umbraco.MetaFields/App_Plugins/SeoToolkit/MetaFields/Interface/ContentApps/DocumentSettings/documentSettings.controller.js, src/SeoToolkit.Umbraco.MetaFields/App_Plugins/SeoToolkit/MetaFields/Interface/ContentApps/SeoSettings/seoSettings.controller.js, src/SeoToolkit.Umbraco.Sitemap/App_Plugins/SeoToolkit/Sitemap/Displays/DocumentType/sitemapSettings.controller.js
=> Prevent multiple initializations on the meta fields content app

src/SeoToolkit.Umbraco.MetaFields.Core/SeoToolkit.Umbraco.MetaFields.Core.csproj, src/SeoToolkit.Umbraco.MetaFields/SeoToolkit.Umbraco.MetaFields.csproj, src/SeoToolkit.Umbraco.MetaFields/build/SeoToolkit.Umbraco.MetaFields.targets, src/SeoToolkit.Umbraco.Redirects.Core/SeoToolkit.Umbraco.Redirects.Core.csproj, src/SeoToolkit.Umbraco.Redirects/SeoToolkit.Umbraco.Redirects.csproj, src/SeoToolkit.Umbraco.RobotsTxt.Core/SeoToolkit.Umbraco.RobotsTxt.Core.csproj, src/SeoToolkit.Umbraco.RobotsTxt/SeoToolkit.Umbraco.RobotsTxt.csproj, src/SeoToolkit.Umbraco.ScriptManager.Core/SeoToolkit.Umbraco.ScriptManager.Core.csproj, src/SeoToolkit.Umbraco.ScriptManager/SeoToolkit.Umbraco.ScriptManager.csproj, src/SeoToolkit.Umbraco.Site/SeoToolkit.Umbraco.Site.csproj, src/SeoToolkit.Umbraco.SiteAudit/SeoToolkit.Umbraco.SiteAudit.csproj, src/SeoToolkit.Umbraco.Sitemap.Core/SeoToolkit.Umbraco.Sitemap.Core.csproj, src/SeoToolkit.Umbraco.Sitemap/SeoToolkit.Umbraco.Sitemap.csproj, src/SeoToolkit.Umbraco.Sitemap/build/SeoToolkit.Umbraco.Sitemap.targets
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/74
=> Fix for app_plugin files not being included for MetaFields and Sitemap

src/SeoToolkit.Umbraco.MetaFields/App_Plugins/SeoToolkit/MetaFields/package.manifest, src/SeoToolkit.Umbraco.Redirects/App_Plugins/SeoToolkit/Redirects/package.manifest, src/SeoToolkit.Umbraco.RobotsTxt/App_Plugins/SeoToolkit/backoffice/RobotsTxt/package.manifest, src/SeoToolkit.Umbraco.ScriptManager/App_Plugins/SeoToolkit/ScriptManager/package.manifest, src/SeoToolkit.Umbraco.SiteAudit/App_Plugins/SeoToolkitSiteAudit/package.manifest, src/SeoToolkit.Umbraco.Sitemap/App_Plugins/SeoToolkit/Sitemap/package.manifest, src/SeoToolkit.Umbraco/App_Plugins/SeoToolkit/backoffice/License/package.manifest
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/59
=> Added umbraco telemetry

src/SeoToolkit.Umbraco.MetaFields.Core/Common/SeoFieldEditors/SeoFieldPropertyEditor.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Interfaces/SeoField/ISeoFieldEditorDefaultValue.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Models/SeoField/CanonicalUrlField.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Models/SeoField/ViewModels/SeoFieldViewModel.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/57
=> Set the default value for canonical url

src/SeoToolkit.Umbraco.Site/ExampleCode/ExampleSitemapNodeNotification.cs, src/SeoToolkit.Umbraco.Site/ExampleCode/ExampleSitemapNotification.cs, src/SeoToolkit.Umbraco.Site/Startup.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Common/SitemapGenerators/SitemapGenerator.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Models/Business/SitemapNodeAlternatePage.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Models/Business/SitemapNodeItem.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Notifications/GenerateSitemapNodeNotification.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Notifications/GenerateSitemapNotification.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/73
=> Allow sitemap extension through notifications

src/SeoToolkit.Umbraco.Sitemap.Core/Migrations/SitemapChangeFrequencyOptionalMigration.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/93
=> 93: Fix for SQLite migration not working

src/SeoToolkit.Umbraco.Common/App_Plugins/SeoToolkit/ContentApps/DocumentType/seoSettings.controller.js
I noticed that the save for document types wasn't always registering. I think this was caused by the individual saves being faster than the global one. This should be fixed with this one.
=> Fix for save not always working

src/SeoToolkit.Umbraco.MetaFields.Core/Notifications/AfterMetaTagsNotification.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Notifications/BeforeMetaTagsNotification.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Providers/DefaultMetaTagsProvider.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Services/DocumentTypeSettings/MetaFieldsSettingsService.cs, src/SeoToolkit.Umbraco.Site/ExampleCode/ExampleAfterMetaTagsNotification.cs, src/SeoToolkit.Umbraco.Site/ExampleCode/ExampleBeforeMetaTagsNotification.cs, src/SeoToolkit.Umbraco.Site/Startup.cs, src/SeoToolkit.Umbraco.Site/appsettings-schema.json
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/99
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/98
Just need to update documentation and then it is good to go!
=> Changed meta tags events to notifications

src/SeoToolkit.Umbraco.Sitemap.Core/Config/Models/SitemapAppSettingsModel.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Config/Models/SitemapConfig.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Config/SitemapConfigurationService.cs, src/SeoToolkit.Umbraco.Sitemap.Core/Middleware/SitemapMiddleware.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/106
=> Change sitemap.xml content type to application/xml instead of text/xml

src/SeoToolkit.Umbraco.MetaFields.Core/Common/SeoFieldEditEditors/SeoImageEditEditor.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Common/SeoFieldEditEditors/SeoTextAreaEditEditor.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Common/SeoFieldEditEditors/SeoTextBoxEditEditor.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/115
=> Use correct name for Linux/Mac systems

src/SeoToolkit.Umbraco.Redirects.Core/Controllers/RedirectsController.cs, src/SeoToolkit.Umbraco.Redirects.Core/Models/ViewModels/RedirectViewModel.cs, src/SeoToolkit.Umbraco.Redirects.Core/Services/RedirectsService.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/118
=> Fix for root level custom domain redirects

src/SeoToolkit.Umbraco.Common.Core/ContentApps/SeoContentAppFactory.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Composers/MetaFieldsComposer.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/122
=> 122: Don't show content app if there is nothing to show

src/SeoToolkit.Umbraco.MetaFields/SeoToolkit.Umbraco.MetaFields.csproj, src/SeoToolkit.Umbraco.Redirects/SeoToolkit.Umbraco.Redirects.csproj, src/SeoToolkit.Umbraco.RobotsTxt/SeoToolkit.Umbraco.RobotsTxt.csproj, src/SeoToolkit.Umbraco.ScriptManager/SeoToolkit.Umbraco.ScriptManager.csproj, src/SeoToolkit.Umbraco.SiteAudit/SeoToolkit.Umbraco.SiteAudit.csproj, src/SeoToolkit.Umbraco.Sitemap/SeoToolkit.Umbraco.Sitemap.csproj, src/SeoToolkit.Umbraco/SeoToolkit.Umbraco.csproj
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/125
=> Added umbraco-marketplace tag

src/SeoToolkit.Umbraco.MetaFields.Core/Common/Converters/SeoValueConverters/FieldSeoValueConverter.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Common/Converters/SeoValueConverters/MultipleMediaSeoValueConverter.cs, src/SeoToolkit.Umbraco.MetaFields.Core/Composers/MetaFieldsComposer.cs
Fixes https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/52
=> Filter out non-images for open graph image
